In [1]:
import pandas as pd

# Replace 'your_file.txt' with the actual filename
df = pd.read_csv("E:\TUS-raw(2019)\TUS106_L01.TXT", header=None, usecols=[0])  # Read only first column

# Extract first 32 alphabets
df['Schedule_Id'] = df[0].str[:3]
df['FSU_Serial_No'] = df[0].str[3:8]
df['Schedule'] = df[0].str[8:11]
df['Survey_Year'] = df[0].str[11:15]
df['Sector'] = df[0].str[15]
df['NSS_Region'] = df[0].str[16:19]
df['District'] = df[0].str[19:21]
df['Stratum'] = df[0].str[21:23]
df['Sub_Stratum'] = df[0].str[23:25]
df['Sub_Round'] = df[0].str[25]
df['FOD_Sub_Region'] = df[0].str[26:30]
df['Sample hhld. No.'] = df[0].str[30:32]
df['Common_Id'] = df[0].str[:32]
df['Level'] = df[0].str[32:34]
df['Filler'] = df[0].str[34:39]
df['Informant Sl.No.'] = df[0].str[39:41]
df['Response Code'] = df[0].str[41]
df['Survey Code'] = df[0].str[42]
df['Substitution Code/ Casualty code'] = df[0].str[43]
df['Filler'] = df[0].str[44:56]
df['Date of Survey'] = df[0].str[56:62]
df['Date of Despatch'] = df[0].str[62:68]
df['Time to canvass(minutes)'] = df[0].str[68:71]
df['No. of investigators(FI/ASO) in the team'] = df[0].str[71]
df['Remarks in block 7'] = df[0].str[72]
df['Remarks in block 8'] = df[0].str[73]
df['Remarks elsewhere in Sch.'] = df[0].str[74]
df['Remarks elsewhere in Sch.'] = df[0].str[75]
df['Blank'] = df[0].str[76:126]
df['NSC'] = df[0].str[126:129]
df['MULT'] = df[0].str[129:139]





# Save to a CSV file (drop original data column)
df.drop(columns=[0], inplace=True)  # Drop the first column (original data)
df.to_csv('File1_updated.csv', index=False)

In [2]:
df = pd.read_csv('File1_updated.csv')

C:\Users\venkat\AppData\Local\Temp\ipykernel_21104\3058279010.py:1: DtypeWarning: Columns (10,22) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('File1_updated.csv')

In [3]:
import pandas as pd

In [4]:
df.shape

(138799, 29)

In [7]:
df.head()

,Schedule_Id,FSU_Serial_No,Schedule,Survey_Year,Sector,NSS_Region,District,Stratum,Sub_Stratum,Sub_Round,...,Date of Survey,Date of Despatch,Time to canvass(minutes),No. of investigators(FI/ASO) in the team,Remarks in block 7,Remarks in block 8,Remarks elsewhere in Sch.,Blank,NSC,MULT
0,TUS,10202,106,2019,1,11,19,1,31,1,...,290119,130219,90,1,2,2,2,...,4,1281550
1,TUS,10202,106,2019,1,11,19,1,31,1,...,260119,130219,90,1,2,2,2,...,4,1281550
2,TUS,10202,106,2019,1,11,19,1,31,1,...,280119,130219,90,1,2,2,2,...,4,1281550
3,TUS,10202,106,2019,1,11,19,1,31,1,...,300119,130219,90,1,2,2,2,...,4,1281550
4,TUS,10202,106,2019,1,11,19,1,31,1,...,270119,130219,90,1,2,2,2,...,4,1281550

In [6]:
df['District'].unique()

array([19, 13, 15, 21,  3,  2,  8,  6, 11, 12, 17,  1,  4, 20, 22,  5,  7,
       16, 18, 10, 14,  9, 27, 23, 28, 32, 30, 29, 25, 33, 24, 31, 26, 44,
       41, 68, 57, 53, 50, 47, 60, 63, 69, 66, 58, 59, 56, 55, 64, 48, 35,
       42, 70, 46, 52, 49, 62, 45, 54, 39, 36, 43, 51, 34, 40, 65, 61, 37,
       67, 71, 38])

In [9]:
df.describe()

,FSU_Serial_No,Schedule,Survey_Year,Sector,NSS_Region,District,Stratum,Sub_Stratum,Sub_Round,Sample hhld. No.,Level,Response Code,Survey Code,Remarks in block 7,Remarks in block 8,Remarks elsewhere in Sch.,NSC,MULT
count,138799.000000,138799.0,138799.0,138799.000000,138799.000000,138799.000000,138799.000000,138799.000000,138799.000000,138799.000000,138799.0,138799.000000,138799.000000,138799.000000,138799.000000,138799.000000,138799.000000,1.387990e+05
mean,17711.246918,106.0,2019.0,1.402755,191.686626,15.756410,2.348295,18.855806,2.498534,7.492813,1.0,1.082731,1.063913,1.918695,1.956520,1.998710,3.995461,2.075041e+05
std,4867.536928,0.0,0.0,0.490454,93.521875,13.315354,1.622986,17.235562,1.117608,4.031078,0.0,0.391602,0.244598,0.273303,0.203936,0.035888,0.145815,1.552374e+05
min,10001.000000,106.0,2019.0,1.000000,11.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000e+00
25%,13471.000000,106.0,2019.0,1.000000,95.000000,6.000000,1.000000,3.000000,2.000000,4.000000,1.0,1.000000,1.000000,2.000000,2.000000,2.000000,4.000000,1.167930e+05
50%,16753.000000,106.0,2019.0,1.000000,194.000000,12.000000,2.000000,10.000000,2.000000,7.000000,1.0,1.000000,1.000000,2.000000,2.000000,2.000000,4.000000,1.996920e+05
75%,22436.000000,106.0,2019.0,2.000000,273.000000,22.000000,3.000000,36.000000,3.000000,11.000000,1.0,1.000000,1.000000,2.000000,2.000000,2.000000,4.000000,2.695745e+05
max,26124.000000,106.0,2019.0,2.000000,362.000000,71.000000,99.000000,63.000000,4.000000,14.000000,1.0,9.000000,2.000000,2.000000,2.000000,2.000000,8.000000,3.145832e+06